server:
  port: 8001
spring:
  application:
    name: mall-registry
eureka:
  instance:
#    hostname: 123.56.245.185
    hostname: 192.168.0.105
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl :
      defaultZone: http://192.168.0.105:8001/eureka/
  server:
    enable-self-preservation: false
