server:
  port: 8301
spring:
  application:
    name: mall-config
  #    默认采用git
  #  profiles:
  #    active: git #使用本地配置，要使用git存储改为git即可
  cloud:
    config:
      server:
        #        native: #本地仓库存储
        #          search-locations: classpath:/config/{application}
        git: #Git仓库存储
          skipSslValidation: true
          uri: https://gitee.com/shad0w/mall-config.git
          #          clone-on-start: true
          search-paths: '{application}'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://123.56.245.185:8001/eureka/
  instance:
    hostname: ${eureka.instance.ip-address} #决定服务跳转host，必须指定
    ip-address: 123.56.245.185 #指定ip 可通过外网访问
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}